server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    max-http-form-post-size: 200MB
spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
logging:
  config: classpath:logback-spring.xml